artifacts_roots: artifacts


data_ingestion: 
  root_dir: artifacts/data_ingestion #root directory for data ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip #the data source on github.com
  local_data_file: artifacts/data_ingestion/data.zip #path to the downloaded data file
  unzip_dir: artifacts/data_ingestion #path to the unzipped data

  
